import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { expect, test } from 'bun:test';

import { generateDockerignore } from '../../src/generators/dockerignore.js';
import { generateGitignore } from '../../src/generators/gitignore.js';
import { generatePrettierignore } from '../../src/generators/prettierignore.js';
import { createConfig } from '../helpers/testConfig.js';

test('keeps maven and python ignore entries in multi-language repositories', async () => {
  // Mirrors a monorepo whose Maven modules and Python lockfiles live in subdirectories only
  // (no root pom.xml / poetry.lock / uv.lock), like WillBoosterLab/judge.
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const config = createConfig({
      dirPath: tempDirPath,
      isRoot: true,
      doesContainPomXmlAnywhere: true,
      doesContainPythonLockAnywhere: true,
    });
    await generateGitignore(config, config);
    const content = fs.readFileSync(path.join(tempDirPath, '.gitignore'), 'utf8');
    expect(content).toMatch(/^target\/$/mu);
    expect(content).toMatch(/^__pycache__\/$/mu);
    expect(content).toMatch(/^\.venv\/$/mu);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('ignores node_modules when the root manifest will be created during this run', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const config = createConfig({
      dirPath: tempDirPath,
      isRoot: true,
      doesContainPackageJson: false,
      packageJson: {},
    });
    await generateGitignore(config, config);

    const content = fs.readFileSync(path.join(tempDirPath, '.gitignore'), 'utf8');
    expect(content).toMatch(/^node_modules\/$/mu);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('keeps repository ignore rules across the first and subsequent runs', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    expect(Bun.spawnSync(['git', 'init', '-q', tempDirPath]).exitCode).toBe(0);
    fs.writeFileSync(path.join(tempDirPath, '.git/info/exclude'), '');
    fs.writeFileSync(
      filePath,
      '\uFEFFbuild/\n# Generated by gitignore.io\n# Native build artifacts\nprebuilds/\n  # Project-specific settings\n# Project-specific settings (tail)\n# project-specific settings (tail)\nsee # Project-specific settings notes\nkeep-me/\n.idea/*\n.vscode/\n.yarn/\n.idea/watcherTasks.xml\n.vscode/settings.json\n.yarn/releases\n'
    );
    const config = createConfig({ dirPath: tempDirPath, isRoot: true });

    await generateGitignore(config, config);
    const firstContent = fs.readFileSync(filePath, 'utf8');
    expect(firstContent).toContain(
      '# Project-specific settings (tail)\nbuild/\n# Generated by gitignore.io\n# Native build artifacts\nprebuilds/\n  # Imported project-specific settings\n# Imported project-specific settings (tail)\n# Imported project-specific settings (tail)\nsee # Imported project-specific settings notes\nkeep-me/\n# .idea/*\n# .vscode/\n# .yarn/\n# .idea/watcherTasks.xml\n# .vscode/settings.json\n# .yarn/releases\n'
    );
    const checkIgnore = (filePath: string): number =>
      Bun.spawnSync(['git', '-c', 'core.excludesFile=/dev/null', 'check-ignore', filePath], {
        cwd: tempDirPath,
      }).exitCode;
    expect(checkIgnore('build/Makefile')).toBe(0);
    expect(checkIgnore('.idea/watcherTasks.xml')).toBe(1);
    expect(checkIgnore('.vscode/settings.json')).toBe(1);
    expect(checkIgnore('.yarn/releases/example.cjs')).toBe(1);

    await generatePrettierignore(config);
    expect(fs.readFileSync(path.join(tempDirPath, '.prettierignore'), 'utf8')).toContain('\nbuild/\n');
    expect(fs.readFileSync(path.join(tempDirPath, '.prettierignore'), 'utf8')).toContain('\nprebuilds/\n');

    await generateGitignore(config, config);
    expect(fs.readFileSync(filePath, 'utf8')).toBe(firstContent);
    expect(checkIgnore('build/Makefile')).toBe(0);
    expect(checkIgnore('prebuilds/example.node')).toBe(0);

    fs.appendFileSync(filePath, 'dist-staging/\n');
    await generateGitignore(config, config);
    expect(fs.readFileSync(filePath, 'utf8')).toContain('dist-staging/\n');
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('retains editable rules from the legacy managed format', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    fs.writeFileSync(
      filePath,
      '\uFEFF# Project-specific settings (head)\r\nlegacy-output/\r\n\r\n# Generated by @willbooster/willboosterify\r\n\r\n# Project-specific settings (Tail) \r\nlocal-cache/\r\n'
    );
    const config = createConfig({ dirPath: tempDirPath, isRoot: true });

    await generateGitignore(config, config);
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('legacy-output/\r\n');
    expect(content).toContain('# Project-specific settings (Tail) \r\nlocal-cache/');

    await generateGitignore(config, config);
    expect(fs.readFileSync(filePath, 'utf8')).toBe(content);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('retains rules prepended to a managed ignore file', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    fs.writeFileSync(
      filePath,
      '# local note\nblocked-at-top/\n# Project-specific settings (head)\ncustom-head-rule/\n# Generated by wbfy\n# Project-specific settings (tail)\nlocal-cache/\n'
    );
    const config = createConfig({ dirPath: tempDirPath, isRoot: true });

    await generateGitignore(config, config);
    await generateGitignore(config, config);
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('blocked-at-top/\n');
    expect(content).toContain('custom-head-rule/\n');
    expect(content).toContain('# Project-specific settings (tail)\nlocal-cache/\n');
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('retains rules above a foreign banner in dockerignore', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.dockerignore');
    fs.writeFileSync(filePath, 'local-secrets.key\n# Generated by some-tool\ndist\n');
    const config = createConfig({ dirPath: tempDirPath, doesContainDockerfile: true });

    await generateDockerignore(config);
    expect(fs.readFileSync(filePath, 'utf8')).toContain('local-secrets.key\n');

    fs.writeFileSync(
      filePath,
      `${fs.readFileSync(filePath, 'utf8').replace('# Project-specific settings (tail)', '# Project-specific settings (Tail) ')}keep-this/\n`
    );
    await generateDockerignore(config);
    expect(fs.readFileSync(filePath, 'utf8')).toContain('keep-this/\n');
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('keeps Tauri lockfiles and source directories visible after migration', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    expect(Bun.spawnSync(['git', 'init', '-q', tempDirPath]).exitCode).toBe(0);
    fs.writeFileSync(path.join(tempDirPath, '.git/info/exclude'), '');
    fs.writeFileSync(filePath, '**/Cargo.lock\n**/debug/\n');
    const defaults = createConfig();
    const config = createConfig({
      dirPath: tempDirPath,
      isRoot: true,
      doesContainTauriConfig: true,
      depending: { ...defaults.depending, tauri: true },
    });

    await generateGitignore(config, config);
    const checkIgnore = (filePath: string): number =>
      Bun.spawnSync(['git', '-c', 'core.excludesFile=/dev/null', 'check-ignore', filePath], {
        cwd: tempDirPath,
      }).exitCode;
    expect(checkIgnore('src-tauri/Cargo.lock')).toBe(1);
    expect(checkIgnore('src/debug/foo.ts')).toBe(1);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});
