import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { expect, test } from 'bun:test';

import { generateGitignore } from '../../src/generators/gitignore.js';
import { promisePool } from '../../src/utils/promisePool.js';
import { createConfig } from '../helpers/testConfig.js';

test('keeps maven and python ignore entries in multi-language repositories', async () => {
  // Mirrors a monorepo whose Maven modules and Python lockfiles live in subdirectories only
  // (no root pom.xml / poetry.lock / uv.lock), like WillBoosterLab/judge.
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const config = createConfig({
      dirPath: tempDirPath,
      isRoot: true,
      doesContainPomXmlAnywhere: true,
      doesContainPythonLockAnywhere: true,
    });
    await generateGitignore(config, config);
    await promisePool.promiseAll();
    const content = fs.readFileSync(path.join(tempDirPath, '.gitignore'), 'utf8');
    expect(content).toMatch(/^target\/$/mu);
    expect(content).toMatch(/^__pycache__\/$/mu);
    expect(content).toMatch(/^\.venv\/$/mu);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('ignores node_modules when the root manifest will be created during this run', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const config = createConfig({
      dirPath: tempDirPath,
      isRoot: true,
      doesContainPackageJson: false,
      packageJson: {},
    });
    await generateGitignore(config, config);
    await promisePool.promiseAll();

    const content = fs.readFileSync(path.join(tempDirPath, '.gitignore'), 'utf8');
    expect(content).toMatch(/^node_modules\/$/mu);
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('keeps repository ignore rules across the first and subsequent runs', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    expect(Bun.spawnSync(['git', 'init', '-q', tempDirPath]).exitCode).toBe(0);
    fs.writeFileSync(
      filePath,
      '# Generated by gitignore.io\n# Native build artifacts\nbuild/\nprebuilds/\n.idea/*\n.vscode/\n.yarn/\n'
    );
    const config = createConfig({ dirPath: tempDirPath, isRoot: true });

    await generateGitignore(config, config);
    await promisePool.promiseAll();
    const firstContent = fs.readFileSync(filePath, 'utf8');
    expect(firstContent).toContain(
      '# Project-specific settings (tail)\n# Generated by gitignore.io\n# Native build artifacts\nbuild/\nprebuilds/\n# .idea/*\n# .vscode/\n# .yarn/\n'
    );
    expect(Bun.spawnSync(['git', 'check-ignore', 'build/Makefile'], { cwd: tempDirPath }).exitCode).toBe(0);
    expect(Bun.spawnSync(['git', 'check-ignore', '.idea/watcherTasks.xml'], { cwd: tempDirPath }).exitCode).toBe(1);
    expect(Bun.spawnSync(['git', 'check-ignore', '.vscode/settings.json'], { cwd: tempDirPath }).exitCode).toBe(1);
    expect(Bun.spawnSync(['git', 'check-ignore', '.yarn/releases/example.cjs'], { cwd: tempDirPath }).exitCode).toBe(1);

    await generateGitignore(config, config);
    await promisePool.promiseAll();
    expect(fs.readFileSync(filePath, 'utf8')).toBe(firstContent);

    fs.appendFileSync(filePath, 'dist-staging/\n');
    await generateGitignore(config, config);
    await promisePool.promiseAll();
    expect(fs.readFileSync(filePath, 'utf8')).toContain('dist-staging/\n');
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});

test('retains editable rules from the legacy managed format', async () => {
  const tempDirPath = await fs.promises.realpath(fs.mkdtempSync(path.join(os.tmpdir(), 'wbfy-gitignore-')));
  try {
    const filePath = path.join(tempDirPath, '.gitignore');
    fs.writeFileSync(
      filePath,
      '# Project-specific settings (head)\nlegacy-output/\n\n# Generated by @willbooster/willboosterify\n\n# Project-specific settings (tail)\nlocal-cache/\n'
    );
    const config = createConfig({ dirPath: tempDirPath, isRoot: true });

    await generateGitignore(config, config);
    await promisePool.promiseAll();
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('legacy-output/\n');
    expect(content).toContain('# Project-specific settings (tail)\nlocal-cache/\n');
  } finally {
    fs.rmSync(tempDirPath, { force: true, recursive: true });
  }
});
