/**
 * Lints a Dockerfile for problems that surface only at deploy time, returning one message per
 * problem (empty when clean).
 */
// These are exactly the failure classes plain BuildKit (local builds, CI) accepts silently, so
// without this check they are first detected by a failed production deploy:
// - Railway's builder rejects every non-cache `RUN --mount` (bind/secret/tmpfs, or an omitted
//   type, which defaults to bind) at Dockerfile validation time with "other mount types are not
//   supported", before any build output.
// - An `ENV`/`ARG` age identity persists in image layers, and a registry reader can decrypt every
//   profile of the committed fnox.toml with it.
// - `COPY` of the root `.env` (or an `.env*` glob) bakes decrypted secrets; only the generated
//   non-secret `.docker.env` (or the legacy `dist/.env`) may be baked.
export function lintDockerfile(dockerfileText: string, options: { railwayConfigured: boolean }): string[] {
  const problems: string[] = [];
  const codeLines = dockerfileText.split('\n').filter((line) => !/^\s*#/.test(line));
  const codeText = codeLines.join('\n');

  if (options.railwayConfigured) {
    for (const match of codeText.matchAll(/--mount=([^\s"'\\]+)/g)) {
      const spec = match[1] ?? '';
      if (!/(?:^|,)type=cache(?:,|$)/.test(spec)) {
        problems.push(
          `Railway's builder rejects \`--mount=${spec}\` at Dockerfile validation time (only type=cache is supported); use COPY or plain commands instead.`
        );
      }
    }
  }

  if (/^\s*(?:ENV|ARG)\s+(?:[^\n=]*\s)?(?:FNOX_AGE_KEY|MISE_AGE_KEY)\b/m.test(codeText)) {
    problems.push(
      'Never persist an age identity in an image: remove the FNOX_AGE_KEY / MISE_AGE_KEY ENV/ARG (pass it as a BuildKit secret where the builder supports one).'
    );
  }

  for (const line of codeLines) {
    const copyMatch = /^\s*COPY\s+(.*)$/i.exec(line);
    if (!copyMatch?.[1]) continue;
    const tokens = copyMatch[1].split(/\s+/).filter((token) => token && !token.startsWith('--'));
    for (const source of tokens.slice(0, -1)) {
      if (source === '.env' || (source.startsWith('.env') && source.includes('*'))) {
        problems.push(
          `\`COPY ${source}\` can bake decrypted secrets into an image layer; bake only the non-secret .docker.env generated by \`wb gen-docker-env\`.`
        );
      }
    }
  }

  return problems;
}
