/**
 * Lints a Dockerfile for problems that surface only at deploy time, returning one message per
 * problem (empty when clean).
 */
// These are exactly the failure classes plain BuildKit (local builds, CI) accepts silently, so
// without this check they are first detected by a failed production deploy:
// - Railway's builder rejects every non-cache `RUN --mount` (bind/secret/tmpfs, or an omitted
//   type, which defaults to bind) at Dockerfile validation time with "other mount types are not
//   supported", before any build output.
// - An `ENV`/`ARG` age identity persists in image layers, and a registry reader can decrypt every
//   profile of the committed fnox.toml with it.
// - `COPY` of the root `.env` (or `.env.<mode>` / `.env*` globs) bakes decrypted secrets; only
//   the generated non-secret `.docker.env` (or the legacy `dist/.env`) may be baked.
export function lintDockerfile(dockerfileText: string, options: { railwayConfigured: boolean }): string[] {
  const problems: string[] = [];
  for (const [instruction, args] of parseLogicalInstructions(dockerfileText)) {
    if (instruction === 'RUN' && options.railwayConfigured) {
      // Mount flags may appear only in the flag section before the command, so a `--mount` inside
      // the shell command itself never triggers a (build-blocking) false positive.
      for (const token of args.split(/\s+/)) {
        if (!token.startsWith('--')) break;
        const mountMatch = /^--mount=(.*)$/.exec(token);
        if (!mountMatch) continue;
        const spec = (mountMatch[1] ?? '').replaceAll(/^["']|["']$/g, '');
        if (!/(?:^|,)type=cache(?:,|$)/.test(spec)) {
          problems.push(
            `Railway's builder rejects \`--mount=${spec}\` at Dockerfile validation time (only type=cache is supported); use COPY or plain commands instead.`
          );
        }
      }
    } else if (
      (instruction === 'ENV' || instruction === 'ARG') &&
      /(^|\s)(FNOX_AGE_KEY|MISE_AGE_KEY)(=|\s|$)/.test(args)
    ) {
      problems.push(
        'Never persist an age identity in an image: remove the FNOX_AGE_KEY / MISE_AGE_KEY ENV/ARG (pass it as a BuildKit secret where the builder supports one).'
      );
    } else if (instruction === 'COPY') {
      for (const source of parseCopySources(args)) {
        // A leading `./` is the same context-root path; deeper paths such as the legacy
        // `dist/.env` and the non-secret `.docker.env` stay allowed.
        const normalized = source.replace(/^\.\//, '');
        if (/^\.env(\..+|\*.*)?$/.test(normalized)) {
          problems.push(
            `\`COPY ${source}\` can bake decrypted secrets into an image layer; bake only the non-secret .docker.env generated by \`wb gen-docker-env\`.`
          );
        }
      }
    }
  }
  return problems;
}

/** Yields `[INSTRUCTION, arguments]` pairs with comments stripped and continuations collapsed. */
function parseLogicalInstructions(dockerfileText: string): [string, string][] {
  const logicalLines = dockerfileText
    .split('\n')
    .filter((line) => !/^\s*#/.test(line))
    .join('\n')
    .replaceAll(/\\\r?\n/g, ' ')
    .split('\n');
  const instructions: [string, string][] = [];
  for (const line of logicalLines) {
    const match = /^\s*([A-Za-z]+)\s+(.*)$/.exec(line);
    if (match?.[1] && match[2]) {
      // Dockerfile instructions are case-insensitive.
      instructions.push([match[1].toUpperCase(), match[2].trim()]);
    }
  }
  return instructions;
}

function parseCopySources(args: string): string[] {
  if (args.startsWith('[')) {
    // JSON (exec) form: COPY ["src", ..., "dst"]
    try {
      const tokens = JSON.parse(args) as unknown;
      if (Array.isArray(tokens) && tokens.every((token) => typeof token === 'string')) {
        return tokens.slice(0, -1);
      }
    } catch {
      // Malformed JSON would fail the docker build itself; nothing to lint.
    }
    return [];
  }
  const tokens = args.split(/\s+/).filter((token) => token && !token.startsWith('--'));
  return tokens.slice(0, -1);
}
