/**
 * Lints a Dockerfile for problems that surface only at deploy time, returning one message per
 * problem (empty when clean).
 */
// These are exactly the failure classes plain BuildKit (local builds, CI) accepts silently, so
// without this check they are first detected by a failed production deploy:
// - Railway's builder rejects every non-cache `RUN --mount` (bind/secret/tmpfs, or an omitted
//   type, which defaults to bind) at Dockerfile validation time with "other mount types are not
//   supported", before any build output.
// - An `ENV`/`ARG` age identity persists in image layers, and a registry reader can decrypt every
//   profile of the committed fnox.toml with it.
// - `COPY` of the root `.env` (or `.env.<mode>` / `.env*` globs) bakes decrypted secrets; only
//   the generated non-secret `.docker.env` (or the legacy `dist/.env`) may be baked.
export function lintDockerfile(dockerfileText: string, options: { railwayConfigured: boolean }): string[] {
  const problems: string[] = [];
  for (const [instruction, args] of parseLogicalInstructions(dockerfileText)) {
    if (instruction === 'RUN' && options.railwayConfigured) {
      // Mount flags may appear only in the flag section before the command, so a `--mount` inside
      // the shell command itself never triggers a (build-blocking) false positive. Quote-aware
      // tokenization keeps a flag whose value contains spaces (e.g. a quoted target) as one token.
      for (const token of tokenizeRespectingQuotes(args)) {
        if (!token.startsWith('--')) break;
        const mountMatch = /^--mount=(.*)$/.exec(token);
        if (!mountMatch) continue;
        const spec = (mountMatch[1] ?? '').replaceAll(/["']/g, '');
        if (!/(?:^|,)type=cache(?:,|$)/.test(spec)) {
          problems.push(
            `Railway's builder rejects \`--mount=${spec}\` at Dockerfile validation time (only type=cache is supported); use COPY or plain commands instead.`
          );
        }
      }
    } else if (
      (instruction === 'ENV' || instruction === 'ARG') &&
      /(^|\s)(FNOX_AGE_KEY|MISE_AGE_KEY)(=|\s|$)/.test(args)
    ) {
      problems.push(
        'Never persist an age identity in an image: remove the FNOX_AGE_KEY / MISE_AGE_KEY ENV/ARG (pass it as a BuildKit secret where the builder supports one).'
      );
    } else if (instruction === 'COPY' || instruction === 'ADD') {
      // ADD copies build-context files into a layer exactly like COPY, so it gets the same check.
      for (const source of parseCopySources(args)) {
        // A leading `./` is the same context-root path; deeper paths such as the legacy
        // `dist/.env` and the non-secret `.docker.env` stay allowed.
        const normalized = source.replace(/^\.\//, '');
        if (/^\.env(\..+|\*.*)?$/.test(normalized)) {
          problems.push(
            `\`${instruction} ${source}\` can bake decrypted secrets into an image layer; bake only the non-secret .docker.env generated by \`wb gen-docker-env\`.`
          );
        }
      }
    }
  }
  return problems;
}

/** Yields `[INSTRUCTION, arguments]` pairs with comments stripped and continuations collapsed. */
function parseLogicalInstructions(dockerfileText: string): [string, string][] {
  const logicalLines = dockerfileText
    .split('\n')
    .filter((line) => !/^\s*#/.test(line))
    .join('\n')
    .replaceAll(/\\\r?\n/g, ' ')
    .split('\n');
  const instructions: [string, string][] = [];
  for (let index = 0; index < logicalLines.length; index++) {
    const line = logicalLines[index] ?? '';
    const match = /^\s*([A-Za-z]+)\s+(.*)$/.exec(line);
    if (!match?.[1] || !match[2]) continue;
    // Dockerfile instructions are case-insensitive.
    const args = match[2].trim();
    instructions.push([match[1].toUpperCase(), args]);
    // Docker treats lines through each heredoc delimiter as part of this instruction, so the
    // body (e.g. a shell command like `env FNOX_AGE_KEY=... fnox export`) must not be parsed
    // as further instructions.
    for (const heredocMatch of args.matchAll(/<<-?["']?([A-Za-z_][A-Za-z0-9_]*)["']?/g)) {
      while (index + 1 < logicalLines.length && logicalLines[++index]?.trim() !== heredocMatch[1]) {
        // Skip the heredoc body.
      }
    }
  }
  return instructions;
}

function parseCopySources(args: string): string[] {
  // Strip leading COPY options (which may precede either form). Sources of a `--from=` COPY come
  // from another stage or context rather than the build-context root, so there is nothing to lint.
  let rest = args.trim();
  while (rest.startsWith('--')) {
    if (rest.startsWith('--from')) return [];
    const flagMatch = /^(?:[^\s"']+|"[^"]*"|'[^']*')+\s*/.exec(rest);
    if (!flagMatch) return [];
    rest = rest.slice(flagMatch[0].length);
  }
  if (rest.startsWith('[')) {
    // JSON (exec) form: COPY ["src", ..., "dst"]
    try {
      const tokens = JSON.parse(rest) as unknown;
      if (Array.isArray(tokens) && tokens.every((token) => typeof token === 'string')) {
        return tokens.slice(0, -1);
      }
    } catch {
      // Malformed JSON would fail the docker build itself; nothing to lint.
    }
    return [];
  }
  // Shell form: strip surrounding quotes so `COPY ".env" "./"` is judged by its real path.
  const tokens = tokenizeRespectingQuotes(rest).map((token) => token.replaceAll(/^["']|["']$/g, ''));
  return tokens.slice(0, -1);
}

/** Splits on whitespace while keeping quoted spans (which may contain spaces) inside one token. */
function tokenizeRespectingQuotes(text: string): string[] {
  return [...text.matchAll(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)].map((match) => match[0]);
}
