import type { PackageConfig } from '../src/packageConfig.js';

export function createConfig(overrides: Partial<PackageConfig> = {}): PackageConfig {
  return {
    dirPath: '/tmp',
    dockerfile: '',
    isRoot: false,
    isPublicRepo: true,
    isReferredByOtherRepo: false,
    repository: 'github:WillBooster/example',
    isWillBoosterRepo: true,
    isCloudflare: false,
    doesContainWranglerConfig: false,
    isRailway: false,
    isBun: false,
    isEsmPackage: false,
    isWillBoosterConfigs: false,
    cargoTomlDirPaths: [],
    doesContainSubPackageJsons: false,
    doesContainDockerfile: false,
    doesContainGemfile: false,
    doesContainGoMod: false,
    doesContainPackageJson: true,
    doesContainPoetryLock: false,
    doesContainUvLock: false,
    doesContainPomXml: false,
    doesContainPubspecYaml: false,
    doesContainTauriConfig: false,
    doesContainTauriConfigInPackages: false,
    doesContainTemplateYaml: false,
    doesContainVscodeSettingsJson: false,
    doesContainJavaScript: false,
    doesContainTypeScript: false,
    doesContainJsxOrTsx: false,
    doesContainJava: false,
    doesContainJavaScriptInPackages: false,
    doesContainTypeScriptInPackages: false,
    doesContainJsxOrTsxInPackages: false,
    doesContainJavaInPackages: false,
    depending: {
      blitz: false,
      chakra: false,
      drizzle: false,
      firebase: false,
      genI18nTs: false,
      litestream: false,
      next: false,
      playwrightRuntime: false,
      playwrightTest: false,
      prisma: false,
      pyright: false,
      react: false,
      reactNative: false,
      semanticRelease: false,
      storybook: false,
      tauri: false,
      vinext: false,
      vite: false,
      wb: false,
    },
    release: {
      branches: [],
      github: false,
      npm: false,
    },
    hasVersionSettings: false,
    miseTasks: {},
    packageJson: {},
    ...overrides,
  };
}
