// GitHub Actions valueless events such as `pull_request:` require YAML null values.
// oxlint-disable eslint-plugin-import/no-named-as-default-member -- Namespace YAML calls make load/dump usage clearer.
/* eslint-disable unicorn/no-null */

import fs from 'node:fs';
import path from 'node:path';

import yaml from 'js-yaml';

import { logger } from '../logger.js';
import type { PackageConfig } from '../packageConfig.js';
import { fsUtil } from '../utils/fsUtil.js';
import { promisePool } from '../utils/promisePool.js';
import { removeTrailingSpaces } from './workflow.js';

/**
 * Repositories outside WillBooster / WillBoosterLab cannot call the organization's reusable
 * workflows: those workflows depend on organization secrets (VERDACCIO_TOKEN, Discord webhooks)
 * and self-hosted runners that other owners do not have. This generator instead emits
 * self-contained workflows built only from what any repository owner can provide: the repository
 * contents (mise.toml, package.json scripts) and the single `FNOX_AGE_KEY` repository secret when
 * the repository uses fnox. Generation is keyed on repository state, never on the owner's
 * identity, so it works for arbitrary personal repositories.
 */

/** First line of every generated file; files without it are hand-written and never touched. */
export const selfContainedWorkflowMarker = '# Generated by wbfy.';

// Same pins as the reusable workflows / their consumers; Renovate updates them in the target repository.
const checkoutAction = 'actions/checkout@v7.0.1';
const miseAction = 'jdx/mise-action@v4.2.3';
const cacheAction = 'actions/cache@v6.1.0';
const uploadArtifactAction = 'actions/upload-artifact@v7.0.1';
// v6.1.1; the same pin as the reusable semantic-pr workflow.
const semanticPullRequestAction = 'amannn/action-semantic-pull-request@45b9ed7cf24087a2f7785bf55be97394ba87e1c2';
// v3.0.3; deploys are network-heavy and benefit from retries with a long timeout.
const retryAction = 'nick-fields/retry@dd56f1ca8ca991e2385c18ab6dd36ea7f9fdb55f';

/**
 * Job-level env that turns the Takumi Guard install path on, mirroring the reusable workflows.
 *
 * `secrets` is unavailable in a step-level `if:`, so the presence of the token is exposed as a
 * non-secret signal; an unset secret expands to `false` and leaves every Guard step skipped, which
 * is what keeps the generated workflows runnable in a repository that never registers the secret.
 * TAKUMI_GUARD_TOKEN itself is defined-but-EMPTY job-wide so the `${TAKUMI_GUARD_TOKEN}` reference
 * in the generated .npmrc still expands (to '') in the steps that deliberately run without the
 * token; a reference to an undefined variable is what breaks an install, an empty one is fine.
 */
const guardJobEnv: Record<string, string> = {
  HAS_TAKUMI_GUARD_TOKEN: '${{ !!secrets.TAKUMI_GUARD_TOKEN }}',
  TAKUMI_GUARD_TOKEN: '',
};

interface Step {
  name?: string;
  id?: string;
  if?: string;
  uses?: string;
  run?: string;
  'working-directory'?: string;
  with?: Record<string, unknown>;
  env?: Record<string, string>;
}

interface Workflow {
  name: string;
  on: Record<string, unknown>;
  concurrency?: Record<string, unknown>;
  permissions?: Record<string, string>;
  jobs: Record<
    string,
    { 'runs-on': string; permissions?: Record<string, string>; env?: Record<string, string>; steps: Step[] }
  >;
}

export async function generateSelfContainedWorkflows(
  rootConfig: PackageConfig,
  allPackageConfigs: PackageConfig[] = [rootConfig]
): Promise<void> {
  return logger.functionIgnoringException('generateSelfContainedWorkflows', async () => {
    const workflowsPath = path.resolve(rootConfig.dirPath, '.github', 'workflows');
    if (!(await fsUtil.isConfinedWritablePath(workflowsPath))) {
      console.warn(`Skipped generating workflows because ${workflowsPath} resolves outside the repository.`);
      return;
    }
    await fs.promises.mkdir(workflowsPath, { recursive: true });

    const usesFnox = fs.existsSync(path.resolve(rootConfig.dirPath, 'fnox.toml'));
    const workflowByFileName: Record<string, Workflow> = {
      'test.yml': buildTestWorkflow(rootConfig, allPackageConfigs, usesFnox),
      'semantic-pr.yml': buildSemanticPrWorkflow(),
    };
    // Deploy workflows are generated per deploy script the repository declares, so a repository
    // without a staging environment simply gets no staging workflow. Only scripts that invoke
    // `wb deploy` qualify: a bespoke deploy script may not be safe to trigger automatically
    // (deploy-staging runs on every push to the default branch).
    const scripts = rootConfig.packageJson?.scripts ?? {};
    const hasProductionDeployWorkflow = isWbDeployScript(scripts['deploy']);
    if (hasProductionDeployWorkflow) {
      workflowByFileName['deploy-production.yml'] = buildDeployWorkflow('production', 'deploy', usesFnox);
    }
    if (isWbDeployScript(scripts['deploy:staging'])) {
      workflowByFileName['deploy-staging.yml'] = buildDeployWorkflow('staging', 'deploy:staging', usesFnox);
    }
    if (rootConfig.depending.semanticRelease && rootConfig.release.branches.length > 0) {
      workflowByFileName['release.yml'] = buildReleaseWorkflow(rootConfig, hasProductionDeployWorkflow, usesFnox);
    }
    for (const [fileName, workflow] of Object.entries(workflowByFileName)) {
      await promisePool.run(() => writeSelfContainedWorkflow(path.join(workflowsPath, fileName), workflow));
    }
  });
}

async function writeSelfContainedWorkflow(filePath: string, workflow: Workflow): Promise<void> {
  const oldContent = await fsUtil.readFileIfExists(filePath);
  // Unlike WillBooster-organization repositories, wbfy does not own arbitrary repositories' CI:
  // only files it generated (identified by the marker) are regenerated, and hand-written
  // workflows are never touched. Owners opt out permanently by removing the marker line.
  // An empty or whitespace-only file carries no hand-written content, so it is treated as absent.
  if (oldContent !== undefined && oldContent.trim() !== '' && !oldContent.startsWith(selfContainedWorkflowMarker)) {
    return;
  }

  const header = `${selfContainedWorkflowMarker} Remove this line to stop wbfy from overwriting this file.\n`;
  const yamlText = yaml.dump(workflow, { lineWidth: -1, noCompatMode: true, styles: { '!!null': 'empty' } });
  await fsUtil.writeFileConfined(filePath, header + removeTrailingSpaces(yamlText));
}

function workingDir(dirPath: string): Pick<Step, 'working-directory'> {
  return dirPath ? { 'working-directory': dirPath } : {};
}

function isWbDeployScript(script: unknown): boolean {
  return typeof script === 'string' && /\bwb deploy\b/u.test(script);
}

function buildTestWorkflow(config: PackageConfig, allPackageConfigs: PackageConfig[], usesFnox: boolean): Workflow {
  // Playwright may be declared only in workspace packages; `wb test-on-ci` runs every declaring
  // package's e2e tests, so the workflow must install browsers for each of them (their versions
  // may differ, and each library version requires its matching browser binaries). Bun's isolated
  // linker resolves the playwright binary only from the declaring package, hence the
  // working-directory on every step. The browsers land in ~/.cache/ms-playwright, shared across
  // workspaces, so same-version installs naturally deduplicate.
  const playwrightDirPaths = [...allPackageConfigs]
    .toSorted((a, b) => a.dirPath.localeCompare(b.dirPath))
    .filter((packageConfig) => packageConfig.depending.playwrightTest)
    .map((packageConfig) => path.relative(config.dirPath, packageConfig.dirPath));
  const hasTypecheck = config.doesContainTypeScript || config.doesContainTypeScriptInPackages;
  // Step-scoped like the reusable test workflow: dependency lifecycle scripts run by `bun install`
  // must not be able to read the long-lived age identity.
  const fnoxEnv: Pick<Step, 'env'> = usesFnox ? { env: { FNOX_AGE_KEY: '${{ secrets.FNOX_AGE_KEY }}' } } : {};

  const steps: Step[] = [
    { uses: checkoutAction },
    { uses: miseAction },
    ...buildInstallSteps(),
    ...(playwrightDirPaths.length > 0
      ? ([
          ...playwrightDirPaths.map(
            (dirPath, index): Step => ({
              name: `Get Playwright version${dirPath ? ` (${dirPath})` : ''}`,
              // The INSTALLED version, not the package.json specifier: a range like `^1.45.0`
              // stays unchanged across lockfile updates, so keying the cache on it would restore
              // stale browsers that no longer match the library. Runs after `bun install`, so the
              // package is resolvable from the declaring package's directory.
              id: `playwright-version-${index}`,
              run: 'echo "version=$(bun -e "try { console.log(require(\'@playwright/test/package.json\').version) } catch {}")" >> "$GITHUB_OUTPUT"',
              ...workingDir(dirPath),
            })
          ),
          {
            name: 'Cache Playwright browsers',
            id: 'playwright-cache',
            uses: cacheAction,
            with: {
              path: '~/.cache/ms-playwright',
              key: `playwright-\${{ runner.os }}-${playwrightDirPaths
                .map((_, index) => `\${{ steps.playwright-version-${index}.outputs.version }}`)
                .join('-')}`,
            },
          },
          ...playwrightDirPaths.map(
            (dirPath): Step => ({
              if: "steps.playwright-cache.outputs.cache-hit != 'true'",
              run: 'bun run playwright install --with-deps',
              ...workingDir(dirPath),
            })
          ),
          ...playwrightDirPaths.map(
            (dirPath): Step => ({
              // The cached browsers still need their system dependencies on a fresh runner.
              if: "steps.playwright-cache.outputs.cache-hit == 'true'",
              run: 'bun run playwright install-deps',
              ...workingDir(dirPath),
            })
          ),
        ] satisfies Step[])
      : []),
    ...(hasTypecheck ? [{ run: 'bun run typecheck', ...fnoxEnv }] : []),
    { run: 'bun run lint', ...fnoxEnv },
    { run: 'bun run test/ci', ...fnoxEnv },
    ...(playwrightDirPaths.length > 0
      ? [
          {
            name: 'Upload test results',
            if: '${{ always() }}',
            uses: uploadArtifactAction,
            with: {
              name: 'test-results',
              // Every declaring package writes its own test-results directory; a newline-separated
              // list uploads them all.
              path: playwrightDirPaths
                .map((dirPath) => (dirPath ? path.posix.join(dirPath, 'test-results') : 'test-results'))
                .join('\n'),
              'if-no-files-found': 'ignore',
              'retention-days': 14,
            },
          },
        ]
      : []),
  ];

  return {
    name: 'Test',
    on: {
      pull_request: null,
      push: { branches: ['main'] },
    },
    concurrency: {
      group: '${{ github.workflow }}-${{ github.ref }}',
      'cancel-in-progress': true,
    },
    permissions: { contents: 'read' },
    jobs: {
      test: {
        'runs-on': 'ubuntu-latest',
        env: { FORCE_COLOR: '3', WB_ENV: 'test', ...guardJobEnv },
        steps,
      },
    },
  };
}

function buildDeployWorkflow(environment: 'staging' | 'production', scriptName: string, usesFnox: boolean): Workflow {
  return {
    name: `Deploy app on ${environment}`,
    on: {
      workflow_dispatch: null,
      // Production deploys follow published releases (see the release workflow's trigger step);
      // staging converges on every default-branch push.
      ...(environment === 'production'
        ? { release: { types: ['published'] } }
        : { push: { branches: ['main'], 'paths-ignore': ['**.md', '**/docs/**'] } }),
    },
    concurrency: {
      group: '${{ github.workflow }}',
      'cancel-in-progress': false,
    },
    permissions: { contents: 'read' },
    jobs: {
      deploy: {
        'runs-on': 'ubuntu-latest',
        env: { WB_ENV: environment, ...guardJobEnv },
        steps: [
          // fetch-depth 0 so `git describe` sees the tags WB_VERSION is derived from.
          { uses: checkoutAction, with: { 'fetch-depth': 0 } },
          { uses: miseAction },
          {
            name: 'Set WB_VERSION',
            run: 'set -euo pipefail\nWB_VERSION=$(git describe --always --tags)\necho "WB_VERSION=$WB_VERSION" >> "$GITHUB_ENV"',
          },
          ...buildInstallSteps(),
          {
            name: 'Deploy',
            uses: retryAction,
            with: {
              timeout_minutes: 60,
              max_attempts: 5,
              command: `bun run ${scriptName}`,
            },
            // Step-scoped like the test workflow: dependency lifecycle scripts run by
            // `bun install` must not be able to read the long-lived age identity.
            ...(usesFnox ? { env: { FNOX_AGE_KEY: '${{ secrets.FNOX_AGE_KEY }}' } } : {}),
          },
        ],
      },
    },
  };
}

function buildReleaseWorkflow(
  config: PackageConfig,
  hasProductionDeployWorkflow: boolean,
  usesFnox: boolean
): Workflow {
  const fnoxEnv: Record<string, string> = usesFnox ? { FNOX_AGE_KEY: '${{ secrets.FNOX_AGE_KEY }}' } : {};
  return {
    name: 'Release',
    on: {
      push: { branches: [...config.release.branches] },
    },
    concurrency: {
      group: '${{ github.workflow }}',
      'cancel-in-progress': false,
    },
    permissions: {
      // for semantic-release
      contents: 'write',
      // for dispatching the production deploy workflow after a release
      ...(hasProductionDeployWorkflow ? { actions: 'write' } : {}),
    },
    jobs: {
      release: {
        'runs-on': 'ubuntu-latest',
        env: { ...guardJobEnv },
        steps: [
          // fetch-depth 0: semantic-release reads the full history to compute the next version.
          { uses: checkoutAction, with: { 'fetch-depth': 0 } },
          { uses: miseAction },
          ...buildInstallSteps(),
          ...(hasProductionDeployWorkflow
            ? [
                {
                  name: 'Get current latest tag',
                  id: 'pre-release-tag',
                  run: 'set -euo pipefail\necho "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo \'\')" >> "$GITHUB_OUTPUT"',
                },
              ]
            : []),
          {
            name: 'Release',
            // Run semantic-release with Node because it checks Node.js runtime requirements.
            run: 'node node_modules/semantic-release/bin/semantic-release.js',
            env: {
              GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
              HUSKY: '0',
              LEFTHOOK: '0',
              ...fnoxEnv,
            },
          },
          ...(hasProductionDeployWorkflow
            ? ([
                {
                  name: 'Check for new release tag',
                  id: 'post-release-tag',
                  run: 'set -euo pipefail\ngit fetch --tags --force\nNEW_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo \'\')\necho "tag=$NEW_TAG" >> "$GITHUB_OUTPUT"\nif [[ -n "$NEW_TAG" && "$NEW_TAG" != "${{ steps.pre-release-tag.outputs.tag }}" ]]; then\n  echo "created=true" >> "$GITHUB_OUTPUT"\nfi',
                },
                {
                  if: "steps.post-release-tag.outputs.created == 'true'",
                  name: 'Trigger production deploy',
                  // A GITHUB_TOKEN-created release does not fire the deploy workflow's
                  // release-published trigger, so dispatch it explicitly on the new tag.
                  run: 'gh workflow run deploy-production.yml --ref "${{ steps.post-release-tag.outputs.tag }}"',
                  env: { GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
                },
              ] satisfies Step[])
            : []),
        ],
      },
    },
  };
}

/**
 * The install sequence every generated workflow shares: a plain `bun install`, hardened into the
 * reusable workflows' three-step dance when the repository registers a TAKUMI_GUARD_TOKEN secret.
 *
 * Takumi Guard (https://flatt.tech/takumi/features/guard) is a registry proxy that blocks
 * known-malicious packages. Routing the DEFAULT registry through it is what protects the install,
 * and the token authenticates that proxy — so the token has to be present while dependencies are
 * resolved, which is exactly when a compromised dependency's lifecycle script would run. Hence the
 * split: resolve and download with `--ignore-scripts` and the token, then replay the skipped
 * lifecycle scripts in a second install that has no token (every package is already cached, and
 * Guard serves anonymously anyway). Only bun is generated here, and bun reads .npmrc, so no
 * package-manager branching is needed.
 *
 * The shell details deliberately mirror reusable-workflows' production-proven install steps: bare
 * `$RUNNER_TEMP` (set by the runner application on every runner, and `set -u` fails loudly if not),
 * `[[ -e .npmrc ]]`, and the second `rm -rf node_modules` in the fallback (an interrupted lifecycle
 * run may leave node_modules inconsistent, so the retry starts clean rather than trusting a repair).
 */
function buildInstallSteps(): Step[] {
  return [
    {
      if: "${{ env.HAS_TAKUMI_GUARD_TOKEN == 'true' }}",
      name: 'Generate .npmrc for Takumi Guard',
      // The token is written as a literal `${TAKUMI_GUARD_TOKEN}` reference that bun expands at
      // install time, so the secret itself never lands in a file. The managed lines are stripped
      // from an existing .npmrc first: a repository outside the organizations may legitimately
      // commit one (scope mappings for another registry), and dropping only these two lines keeps
      // the rest of it in effect. Replacing the file with `mv` rather than appending in place stops
      // a committed symlink from redirecting the write into, say, a persistent home npmrc.
      run: `set -euo pipefail
NPMRC="$(mktemp "$RUNNER_TEMP/npmrc.XXXXXX")"
if [[ -e .npmrc ]]; then
  grep -vE '^registry=|^//npm\\.flatt\\.tech/:_authToken' .npmrc > "$NPMRC" || true
fi
echo 'registry=https://npm.flatt.tech/' >> "$NPMRC"
echo '//npm.flatt.tech/:_authToken=\${TAKUMI_GUARD_TOKEN}' >> "$NPMRC"
rm -f .npmrc
mv "$NPMRC" .npmrc`,
    },
    {
      name: 'Install dependencies',
      run: `set -euo pipefail
if [[ "$HAS_TAKUMI_GUARD_TOKEN" == "true" ]]; then
  bun install --ignore-scripts
else
  bun install
fi`,
      // Step-scoped: a job-level token would be readable by every dependency lifecycle script the
      // tokenless replay below runs.
      env: { TAKUMI_GUARD_TOKEN: '${{ secrets.TAKUMI_GUARD_TOKEN }}' },
    },
    {
      if: "${{ env.HAS_TAKUMI_GUARD_TOKEN == 'true' }}",
      name: 'Run dependency lifecycle scripts without registry credentials',
      // A repeated `bun install` is a no-op that replays nothing, so node_modules has to go first.
      // A failing repository postinstall is tolerated exactly as the reusable workflows tolerate
      // it: the token-free environment also lacks FNOX_AGE_KEY, so a postinstall that wants
      // decrypted secrets cannot succeed here and must not take the whole job down.
      run: `set -euo pipefail
rm -rf node_modules
bun install || {
  echo "::warning::Lifecycle scripts failed; completing the install without them"
  rm -rf node_modules
  bun install --ignore-scripts
}`,
    },
    {
      if: "${{ env.HAS_TAKUMI_GUARD_TOKEN == 'true' }}",
      name: 'Remove the generated .npmrc',
      // Nothing after the install needs the proxy, and leaving it in place would break the one
      // thing Guard refuses to serve: it answers `npm publish` with 405, so a release workflow
      // whose package lacks an explicit publishConfig.registry would fail to publish.
      run: `set -euo pipefail
if git ls-files --error-unmatch -- .npmrc > /dev/null 2>&1; then
  git checkout -- .npmrc
else
  rm -f .npmrc
fi`,
    },
  ];
}

function buildSemanticPrWorkflow(): Workflow {
  return {
    name: 'Lint PR title',
    on: {
      pull_request_target: { types: ['opened', 'edited', 'synchronize'] },
    },
    jobs: {
      'semantic-pr': {
        'runs-on': 'ubuntu-latest',
        // The action reads the pull request, and its `wip` support posts a commit status; neither
        // permission is granted when the repository restricts default workflow permissions.
        permissions: { 'pull-requests': 'read', statuses: 'write' },
        steps: [
          {
            uses: semanticPullRequestAction,
            with: { wip: true },
            env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
          },
        ],
      },
    },
  };
}
