// GitHub Actions valueless events such as `pull_request:` require YAML null values.
// oxlint-disable eslint-plugin-import/no-named-as-default-member -- Namespace YAML calls make load/dump usage clearer.
/* eslint-disable unicorn/no-null */

import fs from 'node:fs';
import path from 'node:path';

import yaml from 'js-yaml';

import { logger } from '../logger.js';
import type { PackageConfig } from '../packageConfig.js';
import { fsUtil } from '../utils/fsUtil.js';
import { promisePool } from '../utils/promisePool.js';

/**
 * Repositories outside WillBooster / WillBoosterLab cannot call the organization's reusable
 * workflows: those workflows depend on organization secrets (VERDACCIO_TOKEN, Discord webhooks)
 * and self-hosted runners that other owners do not have. This generator instead emits
 * self-contained workflows built only from what any repository owner can provide: the repository
 * contents (mise.toml, package.json scripts) and the single `FNOX_AGE_KEY` repository secret when
 * the repository uses fnox. Generation is keyed on repository state, never on the owner's
 * identity, so it works for arbitrary personal repositories.
 */

/** First line of every generated file; files without it are hand-written and never touched. */
export const selfContainedWorkflowMarker = '# Generated by wbfy.';

// Same pins as the reusable workflows / their consumers; Renovate updates them in the target repository.
const checkoutAction = 'actions/checkout@v7.0.1';
const miseAction = 'jdx/mise-action@v4.2.3';
const cacheAction = 'actions/cache@v6.1.0';
const uploadArtifactAction = 'actions/upload-artifact@v7.0.1';
// v6.1.1; the same pin as the reusable semantic-pr workflow.
const semanticPullRequestAction = 'amannn/action-semantic-pull-request@45b9ed7cf24087a2f7785bf55be97394ba87e1c2';

interface Step {
  name?: string;
  id?: string;
  if?: string;
  uses?: string;
  run?: string;
  with?: Record<string, unknown>;
  env?: Record<string, string>;
}

interface Workflow {
  name: string;
  on: Record<string, unknown>;
  concurrency?: Record<string, unknown>;
  permissions?: Record<string, string>;
  jobs: Record<string, { 'runs-on': string; env?: Record<string, string>; steps: Step[] }>;
}

export async function generateSelfContainedWorkflows(rootConfig: PackageConfig): Promise<void> {
  return logger.functionIgnoringException('generateSelfContainedWorkflows', async () => {
    const workflowsPath = path.resolve(rootConfig.dirPath, '.github', 'workflows');
    if (!(await fsUtil.isConfinedWritablePath(workflowsPath))) {
      console.warn(`Skipped generating workflows because ${workflowsPath} resolves outside the repository.`);
      return;
    }
    await fs.promises.mkdir(workflowsPath, { recursive: true });

    const workflowByFileName: Record<string, Workflow> = {
      'test.yml': buildTestWorkflow(rootConfig),
      'semantic-pr.yml': buildSemanticPrWorkflow(),
    };
    for (const [fileName, workflow] of Object.entries(workflowByFileName)) {
      await promisePool.run(() => writeSelfContainedWorkflow(path.join(workflowsPath, fileName), workflow));
    }
  });
}

async function writeSelfContainedWorkflow(filePath: string, workflow: Workflow): Promise<void> {
  const oldContent = await fsUtil.readFileIfExists(filePath);
  // Unlike WillBooster-organization repositories, wbfy does not own arbitrary repositories' CI:
  // only files it generated (identified by the marker) are regenerated, and hand-written
  // workflows are never touched. Owners opt out permanently by removing the marker line.
  if (oldContent !== undefined && !oldContent.startsWith(selfContainedWorkflowMarker)) return;

  const header = `${selfContainedWorkflowMarker} Remove this line to stop wbfy from overwriting this file.\n`;
  const yamlText = yaml.dump(workflow, { lineWidth: -1, noCompatMode: true, styles: { '!!null': 'empty' } });
  await fsUtil.writeFileConfined(filePath, header + removeTrailingSpaces(yamlText));
}

function removeTrailingSpaces(text: string): string {
  // js-yaml emits valueless GitHub Actions events as `event: ` when using the empty null style.
  return text.replaceAll(/[ \t]+$/gm, '');
}

function buildTestWorkflow(config: PackageConfig): Workflow {
  const usesFnox = fs.existsSync(path.resolve(config.dirPath, 'fnox.toml'));
  const usesPlaywright = config.depending.playwrightTest;
  const hasTypecheck = config.doesContainTypeScript || config.doesContainTypeScriptInPackages;
  // Step-scoped like the reusable test workflow: dependency lifecycle scripts run by `bun install`
  // must not be able to read the long-lived age identity.
  const fnoxEnv: Pick<Step, 'env'> = usesFnox ? { env: { FNOX_AGE_KEY: '${{ secrets.FNOX_AGE_KEY }}' } } : {};

  const steps: Step[] = [
    { uses: checkoutAction },
    { uses: miseAction },
    { run: 'bun install' },
    ...(usesPlaywright
      ? ([
          {
            name: 'Get Playwright version',
            id: 'playwright-version',
            run: "echo \"version=$(bun -e \"const p = require('./package.json'); console.log(p.devDependencies?.['@playwright/test'] ?? p.dependencies?.['@playwright/test'] ?? '')\")\" >> \"$GITHUB_OUTPUT\"",
          },
          {
            name: 'Cache Playwright browsers',
            id: 'playwright-cache',
            uses: cacheAction,
            with: {
              path: '~/.cache/ms-playwright',
              key: 'playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}',
            },
          },
          {
            if: "steps.playwright-cache.outputs.cache-hit != 'true'",
            run: 'bun run playwright install --with-deps',
          },
          {
            // The cached browsers still need their system dependencies on a fresh runner.
            if: "steps.playwright-cache.outputs.cache-hit == 'true'",
            run: 'bun run playwright install-deps',
          },
        ] satisfies Step[])
      : []),
    ...(hasTypecheck ? [{ run: 'bun run typecheck', ...fnoxEnv }] : []),
    { run: 'bun run lint', ...fnoxEnv },
    { run: 'bun run test/ci', ...fnoxEnv },
    ...(usesPlaywright
      ? [
          {
            name: 'Upload test results',
            if: '${{ always() }}',
            uses: uploadArtifactAction,
            with: { name: 'test-results', path: 'test-results', 'if-no-files-found': 'ignore', 'retention-days': 14 },
          },
        ]
      : []),
  ];

  return {
    name: 'Test',
    on: {
      pull_request: null,
      push: { branches: ['main'] },
    },
    concurrency: {
      group: '${{ github.workflow }}-${{ github.ref }}',
      'cancel-in-progress': true,
    },
    permissions: { contents: 'read' },
    jobs: {
      test: {
        'runs-on': 'ubuntu-latest',
        env: { FORCE_COLOR: '3', WB_ENV: 'test' },
        steps,
      },
    },
  };
}

function buildSemanticPrWorkflow(): Workflow {
  return {
    name: 'Lint PR title',
    on: {
      pull_request_target: { types: ['opened', 'edited', 'synchronize'] },
    },
    jobs: {
      'semantic-pr': {
        'runs-on': 'ubuntu-latest',
        steps: [
          {
            uses: semanticPullRequestAction,
            with: { wip: true },
            env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
          },
        ],
      },
    },
  };
}
