export const extensions = {
  codeWith2IndentSize: [
    'cjs',
    'mjs',
    'js',
    'jsx',
    'cts',
    'mts',
    'ts',
    'tsx',
    'json',
    'json5',
    'jsonc',
    'cpp',
    'dart',
    'htm',
    'html',
    'pu',
    'puml',
    'rb',
    'vue',
    'xml',
    'yaml',
    'yml',
    'sh',
  ].toSorted(),
  codeWith4IndentSize: ['go', 'gradle', 'java', 'py'].toSorted(),
  markdownLike: ['md'].toSorted(),
  oxlint: ['astro', 'cjs', 'cts', 'js', 'jsx', 'mjs', 'mts', 'svelte', 'ts', 'tsx', 'vue'].toSorted(),
  oxfmt: [
    'astro',
    'cjs',
    'css',
    'cts',
    'gql',
    'graphql',
    'hbs',
    'htm',
    'html',
    'js',
    'json',
    'json5',
    'jsonc',
    'jsx',
    'less',
    'md',
    'mdx',
    'mjs',
    'mts',
    'scss',
    'svelte',
    'toml',
    'ts',
    'tsx',
    'vue',
    'yaml',
    'yml',
  ].toSorted(),
  prettierOnly: ['java'].toSorted(),
};
