import fs from 'node:fs';

const userContentHeader = '# Project-specific settings';
const userContentHeaderRegex = /^\uFEFF?# Project-specific settings[^\r\n]*\r?\n/gm;
const headUserContentHeaderRegex = /^\uFEFF?# Project-specific settings \(head\)\r?\n/mu;
const separator = '# Generated by wbfy';
const separatorPrefix = '# Generated by ';
const legacySeparator = '# Generated by @willbooster/willboosterify';
const defaultHeadUserContent = `${userContentHeader} (head)


${separator}
`;
const defaultTailUserContent = `
${userContentHeader} (tail)
`;

export const ignoreFileUtil = {
  separator,
  defaultHeadUserContent,
  defaultTailUserContent,
  isManaged(content: string): boolean {
    const headIndex = content.search(headUserContentHeaderRegex);
    const separatorIndex = content.indexOf(separatorPrefix, headIndex);
    return headIndex !== -1 && separatorIndex > headIndex && getIndexOfTailUserContentHeader(content) > separatorIndex;
  },
  async readGitignoreWithoutSeparators(filePath: string): Promise<string | undefined> {
    try {
      const content = await fs.promises.readFile(filePath, 'utf8');
      return (
        content
          .replaceAll(userContentHeaderRegex, '')
          .replaceAll(/# Generated by [^\n]*\n/gm, '')
          .replaceAll(/\r?\n\r?\n(\r?\n)+/gm, '\n\n')
          .trim() + '\n'
      );
    } catch {
      // do nothing
    }
  },
  getHeadUserContent(content: string): string {
    const index = content.includes(this.separator)
      ? content.indexOf(this.separator)
      : content.includes(legacySeparator)
        ? content.indexOf(legacySeparator)
        : content.indexOf(separatorPrefix);
    if (index !== -1) {
      return content
        .slice(0, content.indexOf('\n', index) + 1)
        .replaceAll(userContentHeaderRegex, `${userContentHeader} (head)\n`);
    }
    return defaultHeadUserContent;
  },
  getTailUserContent(content: string): string {
    const lastHeaderIndex = getIndexOfTailUserContentHeader(content);
    if (lastHeaderIndex > 0) {
      return content.slice(lastHeaderIndex - 1);
    }
    return defaultTailUserContent;
  },
  async isBerryZeroInstallEnabled(filePath: string): Promise<boolean> {
    try {
      const content = await fs.promises.readFile(filePath, 'utf8');
      return content.includes('\n!.yarn/cache');
    } catch {
      return false;
    }
  },
};

function getIndexOfTailUserContentHeader(content: string): number {
  const index = content.indexOf(userContentHeader);
  const lastIndex = content.lastIndexOf(userContentHeader);
  return lastIndex > index ? lastIndex : -1;
}
