import fs from 'node:fs';

const userContentHeader = '# Project-specific settings';
const userContentHeaderRegex = /^[ \t]*\uFEFF?# Project-specific settings \((head|tail)\)[ \t]*(?:\r?\n|$)/gim;
const separator = '# Generated by wbfy';
const separatorPrefix = '# Generated by ';
const defaultHeadUserContent = `${userContentHeader} (head)


${separator}
`;
const defaultTailUserContent = `
${userContentHeader} (tail)
`;

export const ignoreFileUtil = {
  separator,
  defaultHeadUserContent,
  defaultTailUserContent,
  isManaged(content: string): boolean {
    const headIndex = getSectionHeaderIndex(content, 'head');
    const tailIndex = getSectionHeaderIndex(content, 'tail');
    return headIndex !== -1 && getManagedSeparatorIndex(content, headIndex, tailIndex) !== -1;
  },
  async readGitignoreWithoutSeparators(filePath: string): Promise<string | undefined> {
    try {
      const content = await fs.promises.readFile(filePath, 'utf8');
      return (
        content
          .replaceAll(userContentHeaderRegex, '')
          .replaceAll(/^# Generated by [^\r\n]*\r?\n/gm, '')
          .replaceAll(/\r?\n\r?\n(\r?\n)+/gm, '\n\n')
          .trimStart()
          .replace(/[\r\n]+$/u, '') + '\n'
      );
    } catch {
      // do nothing
    }
  },
  getHeadUserContent(content: string): string {
    const index = this.isManaged(content)
      ? getManagedSeparatorIndex(
          content,
          getSectionHeaderIndex(content, 'head'),
          getSectionHeaderIndex(content, 'tail')
        )
      : content.indexOf(separatorPrefix);
    if (index !== -1) {
      return content
        .slice(0, content.indexOf('\n', index) + 1)
        .replaceAll(userContentHeaderRegex, `${userContentHeader} (head)\n`);
    }
    return defaultHeadUserContent;
  },
  getTailUserContent(content: string): string {
    const lastHeaderIndex = getSectionHeaderIndex(content, 'tail');
    if (lastHeaderIndex > 0) {
      return content.slice(lastHeaderIndex - 1);
    }
    return defaultTailUserContent;
  },
  async isBerryZeroInstallEnabled(filePath: string): Promise<boolean> {
    try {
      const content = await fs.promises.readFile(filePath, 'utf8');
      return content.includes('\n!.yarn/cache');
    } catch {
      return false;
    }
  },
};

function getSectionHeaderIndex(content: string, section: 'head' | 'tail'): number {
  let index = -1;
  for (const match of content.matchAll(userContentHeaderRegex)) {
    if (match[1]?.toLowerCase() === section) index = match.index;
  }
  return index;
}

function getManagedSeparatorIndex(content: string, headIndex: number, tailIndex: number): number {
  for (const match of content.matchAll(/^# Generated by (?:wbfy|@willbooster\/willboosterify)[ \t]*\r?$/gm)) {
    if (match.index > headIndex && match.index < tailIndex) return match.index;
  }
  return -1;
}
