import fs from 'node:fs';
import path from 'node:path';

import type { PackageJson } from 'type-fest';

import { logger } from '../logger.js';
import type { PackageConfig } from '../packageConfig.js';
import { spawnSyncAndReturnStatus, spawnSyncAndReturnStdout } from '../utils/spawnUtil.js';
import { runsManagedGenCode } from '../utils/managedScriptSegment.js';

const workerTypesFileName = 'worker-configuration.d.ts';

/**
 * Stops tracking worker-configuration.d.ts in Cloudflare projects that committed it before .gitignore covered it.
 */
export async function untrackWorkerTypes(config: PackageConfig): Promise<void> {
  return logger.functionIgnoringException('untrackWorkerTypes', async () => {
    // .gitignore is ignored for already-tracked files, so a committed worker-configuration.d.ts would keep
    // producing a huge diff on every wrangler bump despite being regenerated by `wb gen-code` on install.
    const tracked = spawnSyncAndReturnStdout('git', ['ls-files', '--', workerTypesFileName], config.dirPath);
    if (!tracked) return;

    // Untrack only when the (re)generated package.json's install pipeline really regenerates the file through
    // `wb gen-code`: generatePackageJson swallows its own exceptions, so a partial run must not leave the
    // declaration deleted with nothing recreating it on fresh checkouts.
    const packageJson = JSON.parse(
      fs.readFileSync(path.resolve(config.dirPath, 'package.json'), 'utf8')
    ) as PackageJson;
    const scripts = packageJson.scripts ?? {};
    if (!runsManagedGenCode(scripts.postinstall, scripts)) return;

    // Untracking a file the generated .gitignore does not actually cover (e.g. the gitignore.io fetch failed, so the
    // file was never written) would leave it untracked and dirty in the repository, so confirm the rule applies first.
    // `git check-ignore` also honors .git/info/exclude and global excludes, which a fresh clone lacks, so the
    // committed package .gitignore must carry the managed rule itself.
    const gitignorePath = path.resolve(config.dirPath, '.gitignore');
    const hasManagedRule =
      fs.existsSync(gitignorePath) &&
      fs
        .readFileSync(gitignorePath, 'utf8')
        .split('\n')
        .some((line) => line.trim() === `/${workerTypesFileName}`);
    if (!hasManagedRule) return;
    // --no-index makes git report the rule that would apply, instead of reporting nothing because the file is tracked.
    const isIgnored =
      spawnSyncAndReturnStatus(
        'git',
        ['check-ignore', '--quiet', '--no-index', '--', workerTypesFileName],
        config.dirPath
      ) === 0;
    if (!isIgnored) return;

    // --cached keeps the file on disk because type checking needs it before the next install regenerates it.
    spawnSyncAndReturnStatus('git', ['rm', '--cached', '--quiet', '--', workerTypesFileName], config.dirPath);
  });
}
