import { logger } from '../logger.js';
import type { PackageConfig } from '../packageConfig.js';
import { spawnSyncAndReturnStatus, spawnSyncAndReturnStdout } from '../utils/spawnUtil.js';

const workerTypesFileName = 'worker-configuration.d.ts';

/**
 * Stops tracking worker-configuration.d.ts in Cloudflare projects that committed it before .gitignore covered it.
 */
export async function untrackWorkerTypes(config: PackageConfig): Promise<void> {
  return logger.functionIgnoringException('untrackWorkerTypes', async () => {
    // .gitignore is ignored for already-tracked files, so a committed worker-configuration.d.ts would keep
    // producing a huge diff on every wrangler bump despite being regenerated by `wrangler types` on install.
    const tracked = spawnSyncAndReturnStdout('git', ['ls-files', '--', workerTypesFileName], config.dirPath);
    if (!tracked) return;

    // --cached keeps the file on disk because type checking needs it before the next install regenerates it.
    spawnSyncAndReturnStatus('git', ['rm', '--cached', '--quiet', '--', workerTypesFileName], config.dirPath);
  });
}
