import fs from 'node:fs';
import path from 'node:path';

import type { PackageJson } from 'type-fest';

import { postinstallGeneratesWorkerTypes } from '../generators/packageJson.js';
import { logger } from '../logger.js';
import type { PackageConfig } from '../packageConfig.js';
import { spawnSyncAndReturnStatus, spawnSyncAndReturnStdout } from '../utils/spawnUtil.js';

const workerTypesFileName = 'worker-configuration.d.ts';

/**
 * Stops tracking worker-configuration.d.ts in Cloudflare projects that committed it before .gitignore covered it.
 */
export async function untrackWorkerTypes(config: PackageConfig): Promise<void> {
  return logger.functionIgnoringException('untrackWorkerTypes', async () => {
    // .gitignore is ignored for already-tracked files, so a committed worker-configuration.d.ts would keep
    // producing a huge diff on every wrangler bump despite being regenerated by `wrangler types` on install.
    const tracked = spawnSyncAndReturnStdout('git', ['ls-files', '--', workerTypesFileName], config.dirPath);
    if (!tracked) return;

    // Untrack only when the (re)generated package.json's install pipeline really regenerates the file:
    // generatePackageJson swallows its own exceptions, so a partial run must not leave the declaration deleted
    // with nothing recreating it on fresh checkouts.
    const packageJson = JSON.parse(
      fs.readFileSync(path.resolve(config.dirPath, 'package.json'), 'utf8')
    ) as PackageJson;
    if (!postinstallGeneratesWorkerTypes(packageJson.scripts ?? {})) return;

    // Untracking a file the generated .gitignore does not actually cover (e.g. the gitignore.io fetch failed, so the
    // file was never written) would leave it untracked and dirty in the repository, so confirm the rule applies first.
    // --no-index makes git report the rule that would apply, instead of reporting nothing because the file is tracked.
    const isIgnored =
      spawnSyncAndReturnStatus(
        'git',
        ['check-ignore', '--quiet', '--no-index', '--', workerTypesFileName],
        config.dirPath
      ) === 0;
    if (!isIgnored) return;

    // --cached keeps the file on disk because type checking needs it before the next install regenerates it.
    spawnSyncAndReturnStatus('git', ['rm', '--cached', '--quiet', '--', workerTypesFileName], config.dirPath);
  });
}
