name: Add close comment
'on':
  pull_request:
    types:
      - opened
permissions:
  pull-requests: write
jobs:
  close-comment:
    uses: WillBooster/reusable-workflows/.github/workflows/close-comment.yml@main
