name: Lint PR title
'on':
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  semantic-pr:
    permissions:
      pull-requests: read
      statuses: write
    uses: WillBooster/reusable-workflows/.github/workflows/semantic-pr.yml@main
